name: release

on:
  release:
    types: [published]

jobs:
  binaries:
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
          - runner: windows-latest
          - runner: macos-13
          - runner: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.8
      - run: npm ci
      - run: npm run build --workspace extract
      - run: bun run extract-static/scripts/compile.ts
      - name: Upload binary to release
        if: ${{ !env.ACT }}
        run: gh release upload ${{ github.event.release.tag_name }} extract-static/dist/* --clobber
        env:
          GH_TOKEN: ${{ github.token }}

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        registry: [
          { enabled: true, public: true, url: 'https://npm.pkg.github.com', token: GITHUB_TOKEN,  },
          { enabled: true, public: true, url: 'https://registry.npmjs.org', token: NPM_TOKEN,  },
        ]
      fail-fast: false
    steps:
      - name: Early exit
        if: matrix.registry.enabled == false
        run: exit 1
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          registry-url: ${{ matrix.registry.url }}
          scope: '@let-value'
          token: ${{ secrets[matrix.registry.token] }}
      - run: npm ci
      - run: npm run build
      - run: npm publish --workspaces --access ${{ matrix.registry.public && 'public' || 'restricted' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets[matrix.registry.token] }}
